return
{
    configurationEnableWindow = false,
    enable = true,
    invertMonsterList = false,
    showCurrentRoomOnly = true,
    showMonsterStatus = true,
    showMonsterID = false,

    mhpEnableWindow = true,
    mhpChanged = false,
    mhpAnchor = 6,
    mhpX = -52,
    mhpY = -75,
    mhpW = 675,
    mhpH = 64,
    mhpNoTitleBar = "NoTitleBar",
    mhpNoResize = "NoResize",
    mhpNoMove = "NoMove",
    mhpTransparentWindow = true,

    targetEnableWindow = true,
    targetChanged = true,
    targetAnchor = 3,
    targetX = 40,
    targetY = -62,
    targetW = 240,
    targetH = 105,
    targetNoTitleBar = "NoTitleBar",
    targetNoResize = "NoResize",
    targetNoMove = "NoMove",
    targetNoScrollbar = "NoScrollbar",
    targetTransparentWindow = true,
    targetShowMonsterName = false,
    targetShowMonsterStats = true,
    targetShowAccuracyAssist = false,
    targetAccuracyThreshold = 90,
    targetShowActivationRates = 2,
}
