return
{
    configurationEnableWindow = false,
    enable = true,
    invertMonsterList = false,
    showCurrentRoomOnly = true,
    showMonsterStatus = true,
    showMonsterID = false,

    mhpEnableWindow = true,
    mhpHideWhenMenu = true,
    mhpHideWhenSymbolChat = true,
    mhpHideWhenMenuUnavailable = true,
    mhpChanged = false,
    mhpAnchor = 6,
    mhpX = -52,
    mhpY = -75,
    mhpW = 675,
    mhpH = 64,
    mhpNoTitleBar = "NoTitleBar",
    mhpNoResize = "NoResize",
    mhpNoMove = "NoMove",
    mhpTransparentWindow = true,

    targetEnableWindow = true,
    targetChanged = false,
    targetAnchor = 3,
    targetX = 40,
    targetY = -60,
    targetW = 240,
    targetH = 105,
    targetNoTitleBar = "NoTitleBar",
    targetNoResize = "NoResize",
    targetNoMove = "NoMove",
    targetNoScrollbar = "NoScrollbar",
    targetTransparentWindow = true,
    targetShowMonsterName = false,
    targetShowMonsterStats = true,
    targetShowAccuracyAssist = false,
    targetAccuracyThreshold = 90,
    targetEnableActivationRates = false,
    targetEnableActivationRateItems = {
        hell = nil,
        dark = nil,
        blizzard = nil,
        arrest = nil,
        seize = nil,
        chaos = nil,
        havoc = nil,
    },
}
