return
{
    configurationEnableWindow = false,
    enable = true,

    allPlayersEnableWindow = false,
    allHideWhenMenu = false,
    allHideWhenSymbolChat = false,
    allHideWhenMenuUnavailable = false,
    allPlayersChanged = false,
    allPlayersAnchor = 1,
    allPlayersX = 50,
    allPlayersY = 50,
    allPlayersW = 450,
    allPlayersH = 350,
    allPlayersNoTitleBar = "",
    allPlayersNoResize = "",
    allPlayersNoMove = "",
    allPlayersTransparentWindow = false,

    singlePlayersEnableWindow = false,
    singlePlayersShowBarText = false,
    singlePlayersShowBarMaxValue = false,

    players = {
        {
            EnableWindow = true,
            Changed = false,
            Anchor = 3,
            X = 5,
            Y = -5,
            W = 150,
            H = 59,
            NoTitleBar = "NoTitleBar",
            NoResize = "NoResize",
            NoMove = "NoMove",
            NoScrollbar = "NoScrollbar",
            AlwaysAutoResize = "AlwaysAutoResize",
            TransparentWindow = false,
            SD = true,
            Invulnerability = true,
        },
        {
            EnableWindow = true,
            Changed = false,
            Anchor = 3,
            X = 155,
            Y = -5,
            W = 150,
            H = 59,
            NoTitleBar = "NoTitleBar",
            NoResize = "NoResize",
            NoMove = "NoMove",
            NoScrollbar = "NoScrollbar",
            AlwaysAutoResize = "AlwaysAutoResize",
            TransparentWindow = false,
            SD = true,
            Invulnerability = true,
        },
        {
            EnableWindow = true,
            Changed = false,
            Anchor = 3,
            X = 305,
            Y = -5,
            W = 150,
            H = 59,
            NoTitleBar = "NoTitleBar",
            NoResize = "NoResize",
            NoMove = "NoMove",
            NoScrollbar = "NoScrollbar",
            AlwaysAutoResize = "AlwaysAutoResize",
            TransparentWindow = false,
            SD = true,
            Invulnerability = true,
        },
        {
            EnableWindow = true,
            Changed = false,
            Anchor = 3,
            X = 455,
            Y = -5,
            W = 150,
            H = 59,
            NoTitleBar = "NoTitleBar",
            NoResize = "NoResize",
            NoMove = "NoMove",
            NoScrollbar = "NoScrollbar",
            AlwaysAutoResize = "AlwaysAutoResize",
            TransparentWindow = false,
            SD = true,
            Invulnerability = true,
        },
    },
   myself = {
        EnableWindow = true,
        HideWhenMenu = false,
        HideWhenSymbolChat = false,
        HideWhenMenuUnavailable = true,
        ShowName = false,
        ShowBarText = false,
        ShowBarMaxValue = false,
        Changed = true,
        Anchor = 1,
        X = 446,
        Y = 61,
        W = 64,
        H = 68,
        NoTitleBar = "NoTitleBar",
        NoResize = "NoResize",
        NoMove = "NoMove",
        NoScrollbar = "NoScrollbar",
        AlwaysAutoResize = "",
        TransparentWindow = true,
        SD = true,
        Invulnerability = false,
        ShowHPBar = false,
   },
}
